USE myWoodFlooringBusiness;
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_ZipCodeID FOREIGN KEY(ZipCodeID) 
REFERENCES ZipCode(ZipCodeID)
ON UPDATE CASCADE
GO
ALTER TABLE Orders WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) 
REFERENCES Customers(CustomerID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetail WITH CHECK
ADD CONSTRAINT FK_OrderID FOREIGN KEY(OrderID)
REFERENCES Orders(OrderID)
ON UPDATE CASCADE
GO
ALTER TABLE OrderDetail WITH CHECK
ADD CONSTRAINT FK_FloorID FOREIGN KEY(FloorID)
REFERENCES Inventory(FloorID)
ON UPDATE CASCADE
GO 
ALTER TABLE OrderDetail WITH CHECK
ADD CONSTRAINT FK_InstallerID FOREIGN KEY(InstallerID)
REFERENCES Installers(InstallerID)
ON UPDATE CASCADE
GO